Repository yjaiswal05/Leetcode_solutions, pull requests merged in 2022-10, with the labels that each got.

#11 Richest Customer Wealth
  maximum wealth.txt
Labels: HACKTOBERFEST

#12 shuffle the array
  shuffle the array.txt
Labels: HACKTOBERFEST

#13 maximum no of candies
  maximum no of canadies.txt
  maximum numbers of candies.txt
Labels: HACKTOBERFEST

#14 reverse words in a string
  reversewords.cpp
Labels: HACKTOBERFEST-ACCEPTED

#17 array from permutation
  array_from_permu.java
Labels: hacktoberfest-accepted

#18 buy sell stocks
  buy_sell_stocks.java
Labels: hacktoberfest-accepted

#16 array concat
  array_concatenation.java
Labels: hacktoberfest-accepted

#15 arithmetic triplets
  arithmetic_triplets.java
Labels: hacktoberfest-accepted

#22 even number
  evenno_digits.java
Labels: hacktoberfest-accepted

#21 runlength
  decompress_runlength.java
Labels: hacktoberfest-accepted

#20 xor
  decode_xor.java
Labels: hacktoberfest-accepted
